

# This file was *autogenerated* from the file cospectrality.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4)
from sage.all import *
from copy import copy

def spec_tuple(G): #G an adj. matrix
    A = copy(G)
    out = []
    for i in range(_sage_const_1 ,G.nrows()):
        A = A * G
        out.append(A.trace())
    return(out)        


def childbear(G):
    return([spec_tuple(G),
            [spec_tuple(G.delete_rows([i]).delete_columns([i])) for i in range(G.nrows())]])


def re_index(lst):
    # Traverse the list from right to left
    for i in range(len(lst) - _sage_const_1 , -_sage_const_1 , -_sage_const_1 ):
        # Count how many elements to the right are less than lst[i]
        count = sum(_sage_const_1  for j in range(i) if lst[j] < lst[i])
        # Decrease the current term by the count
        lst[i] = lst[i] - count
    return(lst)


def generationbear(G, old_cospectrum):
    k = _sage_const_0 
    cstr = "old_cospectrum" + "[0]"
    while not (isinstance(eval(cstr), Integer) or isinstance(eval(cstr), int)):
        cstr = cstr[:-_sage_const_3 ]
        cstr = cstr + "[1][0][0]"
        k = k + _sage_const_1 

    if k>_sage_const_0 :
        for tup in Permutations([n for n in range(G.nrows())],Integer(k)):
            tup2 = copy(tup)
            tup2 = re_index(tup2)
            cstr = "old_cospectrum"
            for i in range(len(tup2)):
                cstr = cstr + "[1]" + str([tup2[i]])
            exec(cstr + "=" + str(childbear(G.delete_rows(tup).delete_columns(tup))))    
    else:
        old_cospectrum = childbear(G)
    
    return(old_cospectrum)


def order_cospec(G, cospectrum, k):
    for i in range(k, _sage_const_0 , -_sage_const_1 ):
        for tup in Permutations([n for n in range(G.nrows())],Integer(k-_sage_const_1 )):#####
            tup2 = copy(tup)
            tup2 = re_index(tup2)
            cstr = "cospectrum[1]"
            for i in range(len(tup2)):
                cstr = cstr + str([tup2[i]]) + "[1]"
            exec(cstr + ".sort()")
    return(cospectrum)


def cospectrum(G, k):
    if k > G.nrows()-_sage_const_4 :
        raise TypeError("k excessively large")
    cospectrum = spec_tuple(G)
    if k == _sage_const_0 :
        return(cospectrum)
    else:
        for i in range(k):
            cospectrum = generationbear(G, cospectrum)

    #now order branches
    for i in range(k,_sage_const_0 ,-_sage_const_1 ):
        order_cospec(G,cospectrum,i)
        
    return(cospectrum)


def cospectrality_test(G, H, k):
    return(cospectrum(G, k) == cospectrum(H, k))

def how_cospectral(G, H, counter=_sage_const_0 ):
    k = _sage_const_0 
    co_G = spec_tuple(G)
    co_H = spec_tuple(H)
    if co_G != co_H:
        return("Not cospectral")
    else:
        while cospectrum(G,k) == cospectrum(H,k):
            if counter == _sage_const_1 :
                print(str(k)+"-cospectral")
            k = k + _sage_const_1 
            # co_G = generationbear(G, co_G)
            # co_H = generationbear(H, co_H)
            # for i in range(k,0,-1):
            #     order_cospec(G,co_G,i)
            #     order_cospec(H,co_H,i)
            if k == G.nrows() - _sage_const_3 :
                return("Isomorphic")
        return(k-_sage_const_1 )



# test
# G = graphs.HeawoodGraph().adjacency_matrix()
# G = Graph([(1, 0), (1, 2), (1, 3), (1, 4)]).adjacency_matrix()
# H = Graph([(0,1),(1,2),(2,3),(3,0)])
# H.add_vertex(4)
# H = H.adjacency_matrix()

# print(cospectrality_test(G,H,0))
# print(cospectrality_test(G,H,1))
# print(how_cospectral(G,G))

# G = Matrix([
#     [0, 1, 0, 0, 0, 1, 0],
#     [1, 0, 0, 1, 0, 1, 1],
#     [0, 0, 0, 0, 0, 0, 0],
#     [0, 1, 0, 0, 1, 1, 0],
#     [0, 0, 0, 1, 0, 0, 0],
#     [1, 1, 0, 1, 0, 0, 0],
#     [0, 1, 0, 0, 0, 0, 0]
# ])

# H = Matrix([
#     [0, 0, 0, 0, 1, 0, 0],
#     [0, 0, 1, 0, 0, 0, 1],
#     [0, 1, 0, 0, 1, 0, 1],
#     [0, 0, 0, 0, 0, 0, 0],
#     [1, 0, 1, 0, 0, 0, 1],
#     [0, 0, 0, 0, 0, 0, 1],
#     [0, 1, 1, 0, 1, 1, 0]
# ])


# print(cospectrum(H,3)==cospectrum(H,3))
# print(how_cospectral(G,H))

# k = 3
# co_G = cospectrum(G,2)
# co_H = cospectrum(H,2)

# co_G = generationbear(G, co_G)
# co_H = generationbear(H, co_H)

# cospectrum = generationbear(G, cospectrum)

#     #now order branches
#     for i in range(k,0,-1):
#         order_cospec(G,cospectrum,i)

# for i in range(k,0,-1):
#     order_cospec(G,co_G,i)
#     order_cospec(H,co_H,i)

# print(co_H == cospectrum(H,k))
# print(k,co_H==co_G,cospectrum(G,k)==cospectrum(H,k))

