

# This file was *autogenerated* from the file embedding_test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2p1 = RealNumber('2.1'); _sage_const_2 = Integer(2); _sage_const_2p2 = RealNumber('2.2')
from sage.all import *
from cospectrality import *
from copy import copy
from key_cospectrum import *

def circulant(nrow, ncol, vec):
    if len(vec) != ncol:
        raise TypeError("Size mismatch")
    M = []
    for i in range(nrow):
        M.append(copy(vec))
        tmp = vec[-_sage_const_1 ]
        vec.pop()
        vec = [tmp] + vec
    return(Matrix(M))

def J(nrow,ncol):
    return Matrix([[_sage_const_1  for i in range(ncol)] for i in range(nrow)])

def binary_strings_to_sage_matrix(binary_strings):
    matrix_rows = []
    
    # Process each binary string
    for line in binary_strings.split("\n"):
        if line.strip():  # Skip empty lines
            row = [int(bit) for bit in line.strip()]
            matrix_rows.append(row)
    
    # Return actual Sage matrix
    return Matrix(matrix_rows)

def join(G, H, joiner=_sage_const_1 ):
    if joiner == _sage_const_0 :
        joiner = J(G.nrows(),H.ncols()) - J(G.nrows(),H.ncols())
    if joiner == _sage_const_1 :
        joiner = J(G.nrows(),H.ncols())
    if joiner == _sage_const_2p1 :
        joiner = circulant(G.nrows(),H.ncols(),[int((_sage_const_1 +(-_sage_const_1 )**(i-_sage_const_1 ))/_sage_const_2 ) for i in range(H.ncols())])
    if joiner == _sage_const_2p2 :
        joiner = circulant(G.nrows(),H.ncols(),[int((_sage_const_1 +(-_sage_const_1 )**(i))/_sage_const_2 ) for i in range(H.ncols())])
    # Construct the block matrix
    B = block_matrix([[G, joiner],
                      [joiner.transpose(), H]])
    return B



Kriegman_1 = binary_strings_to_sage_matrix("""
0001010101
0000110101
0000011110
1000001011
0100001011
1110000100
0011100010
1110010000
0011101000
1101100000
""")

Kriegman_2 = binary_strings_to_sage_matrix("""
0001010110
0000110011
0000011101
1000001110
0100001011
1110000100
0011100001
1011010000
1101100000
0110101000
""")


star_4 = Matrix([[_sage_const_0 ,_sage_const_1 ,_sage_const_1 ,_sage_const_1 ,_sage_const_1 ],
                 [_sage_const_1 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ],
                 [_sage_const_1 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ],
                 [_sage_const_1 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ],
                 [_sage_const_1 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ]])

pair_star_4 = Matrix([[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ,_sage_const_1 ,_sage_const_0 ],
                 [_sage_const_1 ,_sage_const_0 ,_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],
                 [_sage_const_0 ,_sage_const_1 ,_sage_const_0 ,_sage_const_1 ,_sage_const_0 ],
                 [_sage_const_1 ,_sage_const_0 ,_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],
                 [_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ]])

print(key_cospectrum(Kriegman_1,_sage_const_1 ))
print(key_cospectrum(Kriegman_2,_sage_const_1 ))



# attempt_1 = join(join(Kriegman_1,Kriegman_1,0),Kriegman_1,1)
# attempt_2 = join(join(Kriegman_2,Kriegman_2,0),Kriegman_2,1)
# print(how_cospectral(attempt_1,attempt_2))

# a = block_matrix([[Kriegman_1, Kriegman_1+matrix.identity(10)],
#                       [Kriegman_1+matrix.identity(10), Kriegman_1]])
# b = block_matrix([[Kriegman_2, Kriegman_2+matrix.identity(10)],
#                       [Kriegman_2+matrix.identity(10), Kriegman_2]])

# print(key_how_cospectral(a,b))

# a = Graph(Kriegman_1).cartesian_product(Graph(Kriegman_1))
# a = a.adjacency_matrix()
# b = Graph(Kriegman_2).cartesian_product(Graph(Kriegman_2))
# b = b.adjacency_matrix()

# print(key_cospectrum(a,2)==key_cospectrum(b,2))
# print(key_how_cospectral(a,b))

a = Graph(pair_star_4).strong_product(Graph(star_4))
a = a.adjacency_matrix()
b = Graph(pair_star_4).strong_product(Graph(pair_star_4))
b = b.adjacency_matrix()

print(key_how_cospectral(a,b))

