

# This file was *autogenerated* from the file key_cospectrum.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2)
from sage.all import *
from cospectrality import *
from copy import *

def empty_tree(n, depth):
    if n < _sage_const_0  or depth < _sage_const_0  or n != int(n) or depth != int(depth):
        raise TypeError("Nonnegative integers only")
    if n == _sage_const_0  or depth == _sage_const_0 :
        return(n)
    else:
        children = []
        for j in range(n):
            children.append([empty_tree(n - _sage_const_1 , depth - _sage_const_1 )])
        out = [n, children]
    return(out)

def relabel_tree(tree, vertices, k, bijection):
    for layer in range(_sage_const_1 ,k+_sage_const_1 ):
        for tup in Combinations([n for n in range(vertices)], Integer(layer)):
            #find old_colour
            altered_tup = list(copy(tup))
            altered_tup = re_index(altered_tup)
            tstr = "tree"
            for p in altered_tup:
                tstr = tstr + "[1]" + str([p]) + "[0]" # +1 due to index matching up
            if layer < k:
                tstr = tstr + "[0]"
            old_colour = eval(tstr)
            new_colour = bijection(old_colour)

            for perm in Permutations(tup):
                tstr = "tree"
                # account for shifting of indices after vertex deletions
                altered_perm = list(copy(perm))
                altered_perm = re_index(altered_perm)         

                for p in altered_perm:
                    tstr = tstr + "[1]" + str([p]) + "[0]" # +1 due to index matching up
                if layer < k:
                    tstr = tstr + "[0]"
                exec(tstr + "= new_colour")
    return(tree)

def key_cospectrum(G, k):
    if k == _sage_const_0 :
        return([[[spec_tuple(G),_sage_const_0 ]],[spec_tuple(G)]],[_sage_const_0 ])
    tree = empty_tree(G.nrows(), k)
    key = [[],[]]

    stup = spec_tuple(G)
    key[_sage_const_0 ].append([stup,_sage_const_0 ])
    key[_sage_const_1 ].append(stup)
    tree[_sage_const_0 ] = _sage_const_0 

    for layer in range(_sage_const_1 ,k+_sage_const_1 ):
        for tup in Combinations([n for n in range(G.nrows())], Integer(layer)):
            M = G.delete_rows(tup).delete_columns(tup)
            stup = spec_tuple(M)
            if stup not in key[_sage_const_1 ]:
                key[_sage_const_0 ].append([stup,len(key[_sage_const_1 ])])
                key[_sage_const_1 ].append(stup)
            position = _sage_const_0 
            while stup != key[_sage_const_1 ][position]:
                position = position + _sage_const_1 
            # colour = key[0][position][1]
            colour = position

            for perm in Permutations(tup):
                tstr = "tree"
                # account for shifting of indices after vertex deletions
                altered_perm = list(copy(perm))
                altered_perm = re_index(altered_perm)         

                for p in altered_perm:
                    tstr = tstr + "[1]" + str([p]) + "[0]" # +1 due to index matching up
                if layer < k:
                    tstr = tstr + "[0]"
                exec(tstr + "= colour")

    #now relabel the tree canonically
    tmp = key[_sage_const_1 ]
    tmp.sort() # lex order
    tmp.sort(key=len, reverse=True) #then reverse length order
    key[_sage_const_1 ] = tmp

    bijection = []
    for i in range(_sage_const_1 ,len(key[_sage_const_1 ])):
        pos = _sage_const_0 
        while key[_sage_const_0 ][pos][_sage_const_0 ] != key[_sage_const_1 ][i]:
            pos = pos + _sage_const_1 
        bijection.append(key[_sage_const_0 ][pos][_sage_const_1 ])
    bijection = Permutation(bijection).inverse()
    tree = relabel_tree(tree, G.nrows(), k, bijection)

    #now order tree branches
    for layer in range(k, _sage_const_0 , -_sage_const_1 ):
        for tup in Permutations([n for n in range(G.nrows())],Integer(layer-_sage_const_1 )):#####
            tup2 = copy(tup)
            tup2 = re_index(tup2)
            tstr = "tree"
            for i in tup2:
                tstr = tstr + "[1]" + str([i]) + "[0]"
            tstr = tstr + "[1]"
            exec(tstr + ".sort()")
    

    key = key[_sage_const_1 ]
    return(key, tree)

def key_how_cospectral(G, H):
    switch = True
    i = _sage_const_0 
    while switch == True:
        switch = (key_cospectrum(G,i) == key_cospectrum(H,i))
        i = i+_sage_const_1 
    return(i-_sage_const_2 )


print(key_cospectrum(matrix([[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ,_sage_const_1 ],[_sage_const_1 ,_sage_const_0 ,_sage_const_1 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ,_sage_const_1 ],[_sage_const_1 ,_sage_const_0 ,_sage_const_1 ,_sage_const_0 ]]),_sage_const_2 ))

