

# This file was *autogenerated* from the file Miyazaki.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_5 = Integer(5); _sage_const_3 = Integer(3); _sage_const_6 = Integer(6); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8); _sage_const_9 = Integer(9); _sage_const_10 = Integer(10); _sage_const_14 = Integer(14); _sage_const_11 = Integer(11); _sage_const_12 = Integer(12); _sage_const_15 = Integer(15); _sage_const_13 = Integer(13); _sage_const_16 = Integer(16); _sage_const_17 = Integer(17); _sage_const_18 = Integer(18); _sage_const_19 = Integer(19)
from sage.all import *
from cospectrality import *

Miyazaki_I = [[_sage_const_0 , _sage_const_4 ], [_sage_const_1 , _sage_const_4 ], [_sage_const_2 , _sage_const_5 ], [_sage_const_3 , _sage_const_5 ], [_sage_const_0 , _sage_const_6 ], [_sage_const_2 , _sage_const_6 ], [_sage_const_1 , _sage_const_7 ], [_sage_const_3 , _sage_const_7 ], [_sage_const_0 , _sage_const_8 ], [_sage_const_3 , _sage_const_8 ], [_sage_const_1 , _sage_const_9 ], [_sage_const_2 , _sage_const_9 ], [_sage_const_4 , _sage_const_6 ], [_sage_const_5 , _sage_const_7 ], [_sage_const_10 , _sage_const_14 ], [_sage_const_11 , _sage_const_14 ], [_sage_const_12 , _sage_const_15 ], [_sage_const_13 , _sage_const_15 ], [_sage_const_10 , _sage_const_16 ], [_sage_const_12 , _sage_const_16 ], [_sage_const_11 , _sage_const_17 ], [_sage_const_13 , _sage_const_17 ], [_sage_const_10 , _sage_const_18 ], [_sage_const_13 , _sage_const_18 ], [_sage_const_11 , _sage_const_19 ], [_sage_const_12 , _sage_const_19 ], [_sage_const_14 , _sage_const_16 ], [_sage_const_15 , _sage_const_17 ], [_sage_const_8 , _sage_const_18 ], [_sage_const_9 , _sage_const_19 ]]
Miyazaki_II = [[_sage_const_0 , _sage_const_4 ], [_sage_const_1 , _sage_const_4 ], [_sage_const_2 , _sage_const_5 ], [_sage_const_3 , _sage_const_5 ], [_sage_const_0 , _sage_const_6 ], [_sage_const_2 , _sage_const_6 ], [_sage_const_1 , _sage_const_7 ], [_sage_const_3 , _sage_const_7 ], [_sage_const_0 , _sage_const_8 ], [_sage_const_3 , _sage_const_8 ], [_sage_const_1 , _sage_const_9 ], [_sage_const_2 , _sage_const_9 ], [_sage_const_4 , _sage_const_6 ], [_sage_const_5 , _sage_const_7 ], [_sage_const_10 , _sage_const_14 ], [_sage_const_11 , _sage_const_14 ], [_sage_const_12 , _sage_const_15 ], [_sage_const_13 , _sage_const_15 ], [_sage_const_10 , _sage_const_16 ], [_sage_const_12 , _sage_const_16 ], [_sage_const_11 , _sage_const_17 ], [_sage_const_13 , _sage_const_17 ], [_sage_const_10 , _sage_const_18 ], [_sage_const_13 , _sage_const_18 ], [_sage_const_11 , _sage_const_19 ], [_sage_const_12 , _sage_const_19 ], [_sage_const_14 , _sage_const_16 ], [_sage_const_15 , _sage_const_17 ], [_sage_const_8 , _sage_const_19 ], [_sage_const_9 , _sage_const_18 ]]

def czm_to_sage_mat(edges):

    num_vertices = _sage_const_0 

    for e in edges:
        if e[_sage_const_1 ]+_sage_const_1  > num_vertices:
            num_vertices = e[_sage_const_1 ]+_sage_const_1 

    adj_matrix = Matrix(ZZ, num_vertices, num_vertices, _sage_const_0 )
    
    # For each edge in the list, set the corresponding entries to 1 (assuming an undirected graph)
    for edge in edges:
        u, v = edge
        adj_matrix[u, v] = _sage_const_1 
        adj_matrix[v, u] = _sage_const_1   # Since the graph is undirected
    
    return adj_matrix

MI = czm_to_sage_mat(Miyazaki_I)
MII = czm_to_sage_mat(Miyazaki_II)

print(how_cospectral(MI,MII))

