

# This file was *autogenerated* from the file random_test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_10 = Integer(10); _sage_const_4 = Integer(4)
from cospectrality import *
from key_cospectrum import *
from sage.all import *
from random import randint
from CFI import *
import time

def random_cosp_test(G, H, k):
    if spec_tuple(G) != spec_tuple(H):
        return("Not cospectral")
    
    n = G.nrows()
    seq = []
    while len(seq) < k:
        tmp = randint(_sage_const_0 ,n-_sage_const_1 )
        if tmp not in seq:
            seq.append(tmp)
    
    specs_G = [spec_tuple(G.delete_rows(seq[_sage_const_0 :i]).delete_columns(seq[_sage_const_0 :i])
                         ) for i in range(len(seq)+_sage_const_1 )]
    
    legit_tups = []
    for i in range(_sage_const_1 ,k+_sage_const_1 ):
        for tup in Permutations([t for t in range(n)],Integer(i)):
            if i == _sage_const_1  and spec_tuple(
                H.delete_rows(tup).delete_columns(tup)) in specs_G:
                legit_tups.append(list(tup))
            elif tup[_sage_const_0 :i-_sage_const_1 ] in legit_tups and spec_tuple(
                H.delete_rows(tup).delete_columns(tup)) in specs_G:
                legit_tups.append(list(tup))
        if legit_tups == []:
            return(False, "Not 1-cospectral")
        elif len(legit_tups[-_sage_const_1 ]) < i:
            return(False, "Not "+str(i)+"-cospectral")
    
    return(True, "May be "+str(k)+"-cospectral")

for i in range(_sage_const_10 ):
    start = time.time()
    print(random_cosp_test(
        CFI(S5,_sage_const_0 ),CFI(S5,_sage_const_1 ),
        _sage_const_4 ))
    end = time.time()
    print(end - start)
    print("test",i)

