

# This file was *autogenerated* from the file simple_tests.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2)
from sage.all import *
from cospectrality import *
from copy import copy
from key_cospectrum import *

def edge_count(G):
    return(sum(G.list()))

def empty(G):
    if G.is_zero() == True:
        return(_sage_const_1 )
    else:
        return(_sage_const_0 )
    
def degseq(G):
    degs = []
    for i in range(G.nrows()):
        degs.append(sum(G[i]))
    tmp = sorted(degs)
    tmp.reverse()
    return(tmp)

def ds_1(G):
    n = G.nrows()
    output = []
    seqs = [] 

    for i in range(n):
        newseq = []
        for j in range(n):
            if G[i,j] == _sage_const_1 :
                newseq.append(sum(G[j]))
        newseq = sorted(newseq)
        seqs.append(newseq)

    seqs = sorted(seqs)
    output.append([seqs[_sage_const_0 ],_sage_const_1 ])
    for i in range(_sage_const_1 ,len(seqs)):
        if seqs[i]==seqs[i-_sage_const_1 ]:
            output[-_sage_const_1 ][_sage_const_1 ] = output[-_sage_const_1 ][_sage_const_1 ] + _sage_const_1 
        else:
            output.append([seqs[i],_sage_const_1 ])

    # output = sorted(output)
    return(output)

def edge_3(G):
    n = G.nrows()
    output = []
    ds1s = [ds_1(G.delete_rows([i]).delete_columns([i])) for i in range(n)]
    ds1s = sorted(ds1s)
    output.append([ds1s[_sage_const_0 ],_sage_const_1 ])
    for i in range(_sage_const_1 ,len(ds1s)):
        if ds1s[i]==ds1s[i-_sage_const_1 ]:
            output[-_sage_const_1 ][_sage_const_1 ] = output[-_sage_const_1 ][_sage_const_1 ] + _sage_const_1 
        else:
            output.append([ds1s[i],_sage_const_1 ])

    # output = sorted(output)
    return(output)


def simple_tree(G, k, test):
    tree_base = []
    n = G.nrows()

    if k == _sage_const_0 :
        return([test(G)])
    tree = empty_tree(G.nrows(), k)

    for tup in Combinations([t for t in range(n)], Integer(k)):
        M = G.delete_rows(tup).delete_columns(tup)
        stup = test(M)

        for perm in Permutations(tup):
            tstr = "tree"
            # account for shifting of indices after vertex deletions
            altered_perm = list(copy(perm))
            altered_perm = re_index(altered_perm)         

            for p in altered_perm:
                tstr = tstr + "[1]" + str([p]) + "[0]" # +1 due to index matching up
            exec(tstr + "= stup")

    #now order tree branches
    for layer in range(k, _sage_const_0 , -_sage_const_1 ):
        for tup in Permutations([n for n in range(G.nrows())],Integer(layer-_sage_const_1 )):#####
            tup2 = copy(tup)
            tup2 = re_index(tup2)
            tstr = "tree"
            for i in tup2:
                tstr = tstr + "[1]" + str([i]) + "[0]"
            tstr = tstr + "[1]"
            exec(tstr + ".sort()")

    return(tree)

def simple_test(G,H,k,test):
    if simple_tree(G,k,test) == simple_tree(H,k,test):
        return(True)
    else:
        return(False)

print(simple_tree(Matrix([[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ],
                          [_sage_const_1 ,_sage_const_0 ,_sage_const_1 ],
                          [_sage_const_0 ,_sage_const_1 ,_sage_const_0 ]]),_sage_const_2 ,edge_count))
print(degseq(Matrix([[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ],
                          [_sage_const_1 ,_sage_const_0 ,_sage_const_1 ],
                          [_sage_const_0 ,_sage_const_1 ,_sage_const_0 ]])))

print(edge_3(Matrix([[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ],
                          [_sage_const_1 ,_sage_const_0 ,_sage_const_1 ],
                          [_sage_const_0 ,_sage_const_1 ,_sage_const_0 ]])))

