

# This file was *autogenerated* from the file testing_data.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3)
from sage.all import *
from cospectrality import *
from key_cospectrum import *

G = graphs.HeawoodGraph().adjacency_matrix()
print(key_cospectrum(G,_sage_const_3 ))




# test
# G = graphs.HeawoodGraph().adjacency_matrix()
# G = Graph([(1, 0), (1, 2), (1, 3), (1, 4)]).adjacency_matrix()
# H = Graph([(0,1),(1,2),(2,3),(3,0)])
# H.add_vertex(4)
# H = H.adjacency_matrix()

# print(cospectrality_test(G,H,0))
# print(cospectrality_test(G,H,1))
# print(how_cospectral(G,G))

# G = Matrix([
#     [0, 1, 0, 0, 0, 1, 0],
#     [1, 0, 0, 1, 0, 1, 1],
#     [0, 0, 0, 0, 0, 0, 0],
#     [0, 1, 0, 0, 1, 1, 0],
#     [0, 0, 0, 1, 0, 0, 0],
#     [1, 1, 0, 1, 0, 0, 0],
#     [0, 1, 0, 0, 0, 0, 0]
# ])

# H = Matrix([
#     [0, 0, 0, 0, 1, 0, 0],
#     [0, 0, 1, 0, 0, 0, 1],
#     [0, 1, 0, 0, 1, 0, 1],
#     [0, 0, 0, 0, 0, 0, 0],
#     [1, 0, 1, 0, 0, 0, 1],
#     [0, 0, 0, 0, 0, 0, 1],
#     [0, 1, 1, 0, 1, 1, 0]
# ])


# print(cospectrum(H,3)==cospectrum(H,3))
# print(how_cospectral(G,H))

# k = 3
# co_G = cospectrum(G,2)
# co_H = cospectrum(H,2)

# co_G = generationbear(G, co_G)
# co_H = generationbear(H, co_H)

# cospectrum = generationbear(G, cospectrum)

#     #now order branches
#     for i in range(k,0,-1):
#         order_cospec(G,cospectrum,i)

# for i in range(k,0,-1):
#     order_cospec(G,co_G,i)
#     order_cospec(H,co_H,i)

# print(co_H == cospectrum(H,k))
# print(k,co_H==co_G,cospectrum(G,k)==cospectrum(H,k))

