

# This file was *autogenerated* from the file tree_compressor.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3)
from sage.all import *
from cospectrality import *
from copy import copy
from key_cospectrum import *
import time 

def binary_strings_to_sage_matrix(binary_strings):
    matrix_rows = []
    
    # Process each binary string
    for line in binary_strings.split("\n"):
        if line.strip():  # Skip empty lines
            row = [int(bit) for bit in line.strip()]
            matrix_rows.append(row)
    
    # Return actual Sage matrix
    return Matrix(matrix_rows)

def extract_graph_blocks(input_string):
    # Split the input string into lines
    lines = input_string.strip().split('\n')
    
    # Remove the first and last lines (which contain sentences)
    lines = lines[_sage_const_1 :-_sage_const_1 ]
    
    # Initialize a list to hold the blocks of 0's and 1's
    blocks = []
    current_block = []
    
    # Loop through each line and group them into blocks separated by empty lines
    for line in lines:
        if line.strip():  # If the line is not empty
            current_block.append(line.strip())
        else:
            # If there's an empty line, it signifies the end of the current block
            if current_block:
                blocks.append('\n'.join(current_block))
                current_block = []
    
    # If the last block is not added yet (no empty line at the end)
    if current_block:
        blocks.append('\n'.join(current_block))
    
    return blocks


def tree_structure(G, k, compression_level):
    tree = key_cospectrum(G, k)[_sage_const_1 ]
    pen_bottom = [[] for i in range(k+_sage_const_1 )]

    # layer = k
    for layer in range(k, k-compression_level, -_sage_const_1 ):
        for tup in Permutations([n for n in range(G.nrows())],Integer(layer-_sage_const_1 )):#####
            tup2 = copy(tup)
            tup2 = re_index(tup2)
            tstr = "tree"
            for i in tup2:
                tstr = tstr + "[1]" + str([i]) + "[0]"
            
            # tstr = tstr + "[1]"
            foot = eval(tstr)
            if foot not in pen_bottom[layer]:
                pen_bottom[layer].append(foot)
            
            i = _sage_const_0 
            while pen_bottom[layer][i] != foot:
                i = i + _sage_const_1 
            colour = -(i + _sage_const_1 ) # to distinguish from existing colours
            exec(tstr + "= " + "colour")


    t = _sage_const_0 
    while pen_bottom[_sage_const_0 ] == []:
        del pen_bottom[_sage_const_0 ]
        t = t+_sage_const_1 

    layers = []
    for i in range(len(pen_bottom)):
        layers.append("Layer " + str(i + t) + ":")
        layers.append(pen_bottom[i])
    return(tree, "<-- tree | layers compressed -->" ,layers)


SRG_16 = """
dim=16, degree=6, lambda=2, mu=2

0111111000000000
1011000111000000
1101000000111000
1110000000000111
1000011100100100
1000101010010010
1000110001001001
0100100011100100
0100010101010010
0100001110001001
0010100100011100
0010010010101010
0010001001110001
0001100100100011
0001010010010101
0001001001001110

0111111000000000
1011000111000000
1100100100110000
1100010010001100
1010001000101010
1001001000010101
1000110001000011
0110000001010110
0101000001101001
0100001110000011
0010100010011001
0010010100100101
0001100010100110
0001010100011010
0000101101001100
0000011011110000


TOTAL NUMBER OF STRONGLY REGULAR GRAPHS = 2
"""

Mats = [binary_strings_to_sage_matrix(m) for m in extract_graph_blocks(SRG_16)]


for m in Mats:
    print("BREAK")
    print(tree_structure(m,_sage_const_4 ,_sage_const_3 ))

